### ISSUE TITLE
Need help.!!!

### ISSUE THREAD

**Issue by Amitranjan71** [chobe111/MRI-to-CT-using-GAN#1]
Hey Naivete,
I'm also working on "Generating synthesized CT from MRI data". But the dataset I am currently using for simulation is very small as it contains very few MRI images.
Can you please help me with the link to the dataset you have used in your work?

Thanks in advance,
Amit
Lots of love from INDIA

**Comment by chobe111** [comment]
Hello Amitranjan71

I use private dataset from cooperative medical institution 
if i use that data for other purposes or leak it to the outside world i have a legal problem
for this reason I'm sorry, but I can't give you any data.

I recommend you should find public medical data

myungki cho from South Korea

**Comment by Amitranjan71** [comment]
Ok, I'll try to find any public data then.

Thanks for your reply
